# -------------------------------------------------------------------------------------------------
# The format used in the {timestamp} placeholder (google "Java timestamp format" for options).
# -------------------------------------------------------------------------------------------------
Timestamp_Format: "MMM/dd/yyyy HH:mm:ss aa"

# -------------------------------------------------------------------------------------------------
# * THE FIRST ALIAS IS THE MAIN LABEL, PLEASE DO NOT REMOVE IT. *
# -------------------------------------------------------------------------------------------------
Command_Aliases: [ vouchers, voucher ]

# -------------------------------------------------------------------------------------------------
# What language should we use for messages? If it exists, the language file will be copied
# to your messages/ folder where you can edit it.
# -------------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------------
# The prefix used in front of most chat or console messages
# -------------------------------------------------------------------------------------------------
Prefix: "&8[&eVouchers&8]"

# -------------------------------------------------------------------------------------------------
# We log a console message if an operation takes over the time below (milliseconds).
# Set to -1 to disable.
# -------------------------------------------------------------------------------------------------
Log_Lag_Over_Milis: 100

# -------------------------------------------------------------------------------------------------
# Do not change this value, otherwise it will corrupt your plugin installation!
# -------------------------------------------------------------------------------------------------
Version: 1